### PR TITLE
Add Dockerfile

### LINKED ISSUE #11: Docker container for Chroxy
We want to be able to run Chroxy within a docker container out of the box, so adding Dockerfile to this project would be a good start.

### PR DESCRIPTION
**Pull request by gitviola**
This PR adds a Dockerfile that includes the latest `google-chrome-stable` package (resolves #11).

With kubernetes I run it like this:

**deployment.yml**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler
  namespace: default
  labels:
    app: myApp
    tier: crawler

spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: myApp
      tier: crawler
  template:
    metadata:
      labels:
        app: myApp
        tier: crawler
    spec:
      containers:
        - image: eu.gcr.io/..../...:latest # your consumer
          name: api
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 100Mi
          ports:
            - containerPort: 4000
          env:
          - name: USER_AGENT
            value: ...
          - name: INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        # [START chroxy]
        - name: headless-chrome
          image: eu.gcr.io/..../chroxy:latest # chroxy
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 30m
              memory: 100Mi
          env:
            - name: CHROXY_CHROME_PORT_FROM
              value: "9222"
            - name: CHROXY_CHROME_PORT_TO
              value: "9223"
          ports:
            - containerPort: 9222
            - containerPort: 9223
            - containerPort: 1331
            - containerPort: 1330
        # [END chroxy]
```

**service.yaml**
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: crawler-api
  labels:
    app: myApp
    tier: crawler
spec:
  selector:
    app: myApp
    tier: crawler
  ports:
  - port: 4000
    protocol: TCP
```

### CODE REVIEW

**Comment by holsee** [comment]
Thanks @schurig, much appreciated! 
I am going to remake this PR to target `develop` branch and add a docker-compose file.

**Comment by holsee** [comment]
@schurig I noticed in your deployment config that you expose:
```
            - containerPort: 9222
            - containerPort: 9223
```

**Comment by holsee** [comment]
@schurig I noticed in your deployment config that you expose:
```
            - containerPort: 9222
            - containerPort: 9223
```
This is not required, unless you are bypassing the Chroxy proxying and want access to the entire browser session (which is a valid use case 👍)

By design, Chroxy exposes a single _magic_ port 1331 which routes the websocket connection to the Chrome processes via a _transparent proxy_.

This mean you don't need to expose the chrome remote debug protocol ports from the host (and can then freely configure Chroxy to start more / less chrome instances) by expanding the port range in the configuration scaling the chrome browser processes running on each host without needing to change the port which you are using to connect to the hosts.

https://github.com/holsee/chroxy/blob/master/config/config.exs#L33-L35
```elixir
config :chroxy,
  chrome_remote_debug_port_from: envar.("CHROXY_CHROME_PORT_FROM") || "9222",
  chrome_remote_debug_port_to: envar.("CHROXY_CHROME_PORT_TO") || "9223"
```

Example: using https://github.com/holsee/chroxy_client for simplicity connecting to local chroxy instance running in docker.

Create a connection to a Chrome "Page" (tab)
```elixir
iex(2)> ChroxyClient.page_session!

15:11:02.122 [debug] WebSocket: ws://127.0.0.1:1331/devtools/page/C78FF247D6E980B694F522DDC9B86F44
#PID<0.212.0>
```

Logs showing that the *other* `ChromeServer` (Chrome OS Process) was selected:
```
 14:07:15.366 pid=<0.352.0> module=Plug.Logger [info]  GET /api/v1/connection

 14:07:15.573 pid=<0.353.0> module=Chroxy.ChromeProxy [debug] Obtained new page from ChromeServer [#PID<0.236.0>]
```

And then a Proxy Server is spawned to route the connection from `ws://127.0.0.1:1331/devtools/page/C78FF247D6E980B694F522DDC9B86F44` which was returned to that of the underlying Chrome Server which is in the range  9222 -9223 but does not need exposed from the host.

```
 14:07:15.574 pid=<0.341.0> module=Chroxy.ProxyRouter [debug] put object with key: B75A9B2AB1E34316C93618E991E7E33D - value: #PID<0.353.0>

 14:07:15.574 request_id=2mavj3hd92mapbdppk000071 pid=<0.352.0> module=Plug.Logger [info]  Sent 200 in 207ms

 14:07:15.577 pid=<0.232.0> module=Chroxy.ProxyListener [info]  Connection accepted, spawning proxy server to manage connection

 14:07:15.578 pid=<0.354.0> module=Chroxy.ProxyServer [debug] Resolved dynamic hook `%{mod: Chroxy.ChromeProxy, ref: #PID<0.353.0>}` for ProxyServer

 14:07:15.579 pid=<0.354.0> module=Chroxy.ProxyServer [debug] Downstream connection established
```

Create another connection to a Chrome "Page" (tab):
```elixir
iex(2)> ChroxyClient.page_session!

15:11:03.392 [debug] WebSocket: ws://127.0.0.1:1331/devtools/page/BBA5475CEF7AF4BD08118F54F4FE03DF
#PID<0.213.0>
```

Logs showing that the *other* `ChromeServer` (Chrome OS Process) was selected, but the `ws://` url still goes via 1331.
```
 14:07:20.721 pid=<0.355.0> module=Plug.Logger [info]  GET /api/v1/connection

 14:07:20.927 pid=<0.356.0> module=Chroxy.ChromeProxy [debug] Obtained new page from ChromeServer [#PID<0.342.0>]
```

Hope that helps, any questions feel free to ask!

**Comment by gitviola** [comment]
@holsee oh, thank you so much for writing this!!

**Pull request closed without merging**
